ci: add some automation
dont-rely-on-nulls/zerl pull request #17
Opened 2024-11-02 11:18 UTC by mtrsk

2024-11-02 12:26 UTC, mtrsk commented
@z-silver can you help me out with this later? the pure build (`nix build`) is almost working

2024-11-03 03:36 UTC, z-silver requested changes
Even if the build doesn't quite work, this is certainly an improvement over what we currently have.

2024-11-03 03:36 UTC, z-silver commented on flake.nix
> +        # Zig shit (Incomplete)
```suggestion
        # Zig
```

2024-11-03 16:03 UTC, z-silver approved these changes
Thank you.

2024-11-03 17:57 UTC, merged